M48
; DRILL file {KiCad 9.0.7} date 2026-04-28T17:35:34-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-28T17:35:34-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.100
%
G90
G05
T1
X122.75Y-59.65
X122.75Y-64.65
T2
X88.0Y-57.5
X88.0Y-60.5
T3
X89.0Y-51.5
X89.0Y-76.5
X124.5Y-51.5
X124.5Y-76.5
M30
